# Add `:lodestar-vc.yml` to `COMPOSE_FILE` in `.env` to use
version: '3.8'

services:

  validator:
    image: chainsafe/lodestar:latest
    platform: linux/amd64
    container_name: validator
    hostname: validator
    restart: unless-stopped
    command:
      - validator
      - --dataDir
      - /var/lib/lodestar/validators
      - --beaconNodes
      - ${CONSENSUS_CLIENT_URL}
      - --keymanager
      - --keymanager.address
      - 0.0.0.0
      - --keymanager.port
      - "7500"
      - --network
      - goerli
      - --externalSigner.url
      - http://diva:9000
      - --externalSigner.fetch
    volumes:
      - ${DIVA_DATA_FOLDER:-.}/lodestar/validators:/var/lib/lodestar/validators
    networks:
      default:
        aliases:
          - vc-rkm

  reloader:
    image: diva/reloader:${RELOADER_VERSION:-v23.8.0}
    platform: linux/amd64
    container_name: reloader
    hostname: reloader
    restart: unless-stopped
    volumes:
      - ${DIVA_DATA_FOLDER:-.}/lodestar/validators/validator-db:/jwt
    environment:
      - VALIDATOR_RKM_API=http://vc-rkm:7500
      - DIVA_W3S_API=http://diva:9000
      - SYNC_PERIOD=600
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while [ ! -f /jwt/api-token.txt ]; do
          sleep 1
          echo "Waiting for Lodestar to create keymanager auth token"
        done
        cp /jwt/api-token.txt /jwt/auth-token
        exec /bin/sh /reload.sh
